/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

/**
 *
 * @author reych
 */
public class nuevo extends javax.swing.JFrame {

    /**
     * Creates new form nuevo
     */
    public nuevo() {
        initComponents();
         this.setTitle("Nuevo Registro");
        this.setLocation(600, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ndc = new javax.swing.JTextField();
        ac = new javax.swing.JTextField();
        nomcre = new javax.swing.JTextField();
        catcaja = new javax.swing.JTextField();
        tipocre = new javax.swing.JTextField();
        tipocar = new javax.swing.JTextField();
        catinv = new javax.swing.JTextField();
        stascon = new javax.swing.JTextField();
        catsta = new javax.swing.JTextField();
        montootor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        montomi = new javax.swing.JTextField();
        numcontra = new javax.swing.JTextField();
        montoauto = new javax.swing.JTextField();
        montoeje = new javax.swing.JTextField();
        carte = new javax.swing.JTextField();
        castiga = new javax.swing.JTextField();
        pequepro = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nc = new javax.swing.JTextField();
        ca1 = new com.toedter.calendar.JDateChooser();
        ca2 = new com.toedter.calendar.JDateChooser();
        ca3 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numero de cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Actividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Numero de credito");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setText("Categoria de producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setText("Tipo de credito");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setText("Tipo de cartera");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setText("Fecha de apertura");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel9.setText("Fecha de vencimiento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel10.setText("Fecha de ministra");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel11.setText("Categoria de inversion");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel12.setText("Status contable");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel13.setText("Cat_status");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel14.setText("Monto otorgado");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        ndc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndcActionPerformed(evt);
            }
        });
        getContentPane().add(ndc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, -1));
        getContentPane().add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));
        getContentPane().add(nomcre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, -1));
        getContentPane().add(catcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, -1));
        getContentPane().add(tipocre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 190, -1));
        getContentPane().add(tipocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 190, -1));
        getContentPane().add(catinv, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 140, -1));
        getContentPane().add(stascon, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 140, -1));
        getContentPane().add(catsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 140, -1));
        getContentPane().add(montootor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 140, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 100, 60));

        jButton2.setText("Volver");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 80, 40));

        jLabel15.setText("Monto ministra");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel16.setText("Numero de contrato");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel17.setText("Monto auto");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel18.setText("Monto ejecutivo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel19.setText("Cartera");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel20.setText("Castigado");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel21.setText("pequeño productor");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        montomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montomiActionPerformed(evt);
            }
        });
        getContentPane().add(montomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, -1));

        numcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcontraActionPerformed(evt);
            }
        });
        getContentPane().add(numcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 140, -1));
        getContentPane().add(montoauto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 140, -1));
        getContentPane().add(montoeje, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 140, -1));

        carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteActionPerformed(evt);
            }
        });
        getContentPane().add(carte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 130, -1));
        getContentPane().add(castiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 130, -1));
        getContentPane().add(pequepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 130, -1));

        jButton3.setText("Modificar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 100, 60));

        jLabel22.setText("Nuevo registro");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel23.setText("Nombre Completo");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(nc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, -1));
        getContentPane().add(ca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 130, -1));
        getContentPane().add(ca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 130, -1));
        getContentPane().add(ca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 130, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ndcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndcActionPerformed

    private void montomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montomiActionPerformed

    private void numcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcontraActionPerformed

    private void carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
                    String b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14,b15,b16,b17,b18,b19,b20,b21;
        
        b1 = nc.getText();
        b2 = ndc.getText();
        b3 = ac.getText();
        b4 = nomcre.getText();
        b5 = catcaja.getText();
        b6 = tipocre.getText();
        b7 = tipocar.getText();
        b8 = montomi.getText();
        b9 = numcontra.getText();
        b10 = montoauto.getText();
        b11 = montoeje.getText();
        b12 =ca1.toString();
        b13 =ca2.toString();
        b14 =ca3.toString();
        b15 =catinv.getText();
        b16 =stascon.getText();
        b17 =catsta.getText();
        b18 =montootor.getText();
        b19 = carte.getText();
        b20 =castiga.getText();
        b21 =pequepro.getText();
                
        
       if (nc.getText().equals("") || (ndc.getText().equals("")) || (ac.getText().equals(""))
           || (nomcre.getText().equals("")) || (catcaja.getText().equals("")) || (tipocre.getText().equals("")) || (tipocar.getText().equals("")) 
               || (montomi.getText().equals("")) || (numcontra.getText().equals("")) || (montoauto.getText().equals("")) || (montoeje.getText().equals("")) 
               || (ca1.toString().equals("")) || (ca2.toString().equals("")) || (ca3.toString().equals("")) || (catinv.getText().equals("")) || (stascon.getText().equals("")) 
               || (catsta.getText().equals("")) || (montootor.getText().equals(""))  || (carte.getText().equals("")) || (castiga.getText().equals("")) || (pequepro.getText().equals("")))   {
            
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           ndc.requestFocus();
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     Bien Expedientes =new Bien();
     Expedientes.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac;
    private com.toedter.calendar.JDateChooser ca1;
    private com.toedter.calendar.JDateChooser ca2;
    private com.toedter.calendar.JDateChooser ca3;
    private javax.swing.JTextField carte;
    private javax.swing.JTextField castiga;
    private javax.swing.JTextField catcaja;
    private javax.swing.JTextField catinv;
    private javax.swing.JTextField catsta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField montoauto;
    private javax.swing.JTextField montoeje;
    private javax.swing.JTextField montomi;
    private javax.swing.JTextField montootor;
    private javax.swing.JTextField nc;
    private javax.swing.JTextField ndc;
    private javax.swing.JTextField nomcre;
    private javax.swing.JTextField numcontra;
    private javax.swing.JTextField pequepro;
    private javax.swing.JTextField stascon;
    private javax.swing.JTextField tipocar;
    private javax.swing.JTextField tipocre;
    // End of variables declaration//GEN-END:variables
}
